    # NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [60]:
import numpy as np

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [61]:
x = np.arange(0, 6)

- Laat de vorm (grootte van de dimensies) van de array zien

In [62]:
np.shape(x)

(6,)

- Hervorm de array x tot een 2D array (2, 3) 

In [63]:
x = np.reshape(x, (2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

- Wat is nu de vorm?


In [64]:
np.shape(x)

(2, 3)

- Laat het datatype zien


In [65]:
type(x)

numpy.ndarray

- Sla een kopie van de array op in y


In [66]:
y = np.copy(x)

- Maak een transpose van x



In [67]:
x = np.transpose(x)

- Maak een transpose van y


In [68]:
y = np.transpose(y)
y

array([[0, 3],
       [1, 4],
       [2, 5]])

- Vermenigvuldig alle waarden van y met 2


In [69]:
y = np.multiply(y, 2)
y

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

- Concateneer de twee arrays in een nieuwe array `z`


In [70]:
z = np.concatenate((x, y), axis=0)
z

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [ 0,  6],
       [ 2,  8],
       [ 4, 10]])

- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [71]:
z_mean = np.mean(z)
z_median = np.median(z)
z_std = np.std(z)

<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [72]:
import math
import random
import numpy as np

In [73]:
lst1 = [random.randint(0, 10) for _ in range(10000001)]
lst2 = [random.randint(0, 10) for _ in range(10000001)]

def py_median(x):
    if len(x) % 2 == 0:
        idx_l = math.floor((len(x) -1) / 2)
        idx_r = math.ceil((len(x) -1) / 2)
        return (x[idx_l] + x[idx_r]) / 2
    else:
        idx = int(len(x) / 2)
        return x[idx]
        
def py_square(x):
    return [math.sqrt(i) for i in x]

def py_even(x):
    return [x for x in x if x % 2 == 0]


def py_sum(x, y):
    z = x + y   
    print(sum(z))
    
py_median(lst1)
py_square(lst1)
py_even(lst1)
py_sum(lst1, lst2)

100018752


In [74]:
lst3 = np.random.randint(0, 10, 10000001)
lst4 = np.random.randint(0, 10, 10000001)

def np_median(x):
    return np.median(x)
        
def np_square(x):
    return np.sqrt(x)

def np_even(x):
    return x[x % 2 == 0]

def np_sum(x, y):
    return np.sum(x + y)
        
np_median(lst3)
np_square(lst3)
np_even(lst3)
np_sum(lst3, lst4)


89969977

<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [75]:
import numpy as np

Start met de data verzamelen:
- Lees tekstbestand: blokAcijfers.txt in met `np.loadtxt`, sla de data op in een numpy array met naam `vCijfers`.
- Laat zien dat de gegevens goed ingelezen zijn.
- Toon de array attributen.

In [76]:
vCijfers = np.loadtxt('blokAcijfers.txt')
vCijfers

array([[6.5, 7.3, 6.4],
       [8. , 8. , 8.5],
       [3.2, 4. , 5. ],
       [7.9, 7.1, 3.5],
       [7.3, 7.8, 8. ],
       [8.6, 8. , 9. ],
       [4. , 6. , 5.5],
       [7.3, 7.8, 7.8],
       [4.5, 5.6, 7.7],
       [5. , 7. , 7.2]])

De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [77]:
vCijfers[2, 1] = 4.3
vCijfers[9, 0] = 4.6
vCijfers

array([[6.5, 7.3, 6.4],
       [8. , 8. , 8.5],
       [3.2, 4.3, 5. ],
       [7.9, 7.1, 3.5],
       [7.3, 7.8, 8. ],
       [8.6, 8. , 9. ],
       [4. , 6. , 5.5],
       [7.3, 7.8, 7.8],
       [4.5, 5.6, 7.7],
       [4.6, 7. , 7.2]])

De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [78]:
for i in vCijfers:
    print(f"Min: {np.min(i)}")

Min: 6.4
Min: 8.0
Min: 3.2
Min: 3.5
Min: 7.3
Min: 8.0
Min: 4.0
Min: 7.3
Min: 4.5
Min: 4.6


In [79]:
for i in vCijfers:
    print(f"Max: {np.max(i)}")

Max: 7.3
Max: 8.5
Max: 5.0
Max: 7.9
Max: 8.0
Max: 9.0
Max: 6.0
Max: 7.8
Max: 7.7
Max: 7.2


In [80]:
for i in vCijfers:
    print(f"Mean: {np.mean(i)}")

Mean: 6.733333333333334
Mean: 8.166666666666666
Mean: 4.166666666666667
Mean: 6.166666666666667
Mean: 7.7
Mean: 8.533333333333333
Mean: 5.166666666666667
Mean: 7.633333333333333
Mean: 5.933333333333334
Mean: 6.266666666666667


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [81]:
vCijfers2 = np.copy(vCijfers)
np.round(vCijfers2)

array([[6., 7., 6.],
       [8., 8., 8.],
       [3., 4., 5.],
       [8., 7., 4.],
       [7., 8., 8.],
       [9., 8., 9.],
       [4., 6., 6.],
       [7., 8., 8.],
       [4., 6., 8.],
       [5., 7., 7.]])

Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [82]:
ophoogarray = np.zeros((10,3))
ophoogarray[:,0] += 0.5 
vCijfers2 += ophoogarray
vCijfers2

array([[7. , 7.3, 6.4],
       [8.5, 8. , 8.5],
       [3.7, 4.3, 5. ],
       [8.4, 7.1, 3.5],
       [7.8, 7.8, 8. ],
       [9.1, 8. , 9. ],
       [4.5, 6. , 5.5],
       [7.8, 7.8, 7.8],
       [5. , 5.6, 7.7],
       [5.1, 7. , 7.2]])

In [83]:
isVld = vCijfers2 >= 5.5
isVld

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [84]:
import numpy as np

#### 3. Create a null vector of size 10

In [85]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [86]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

In [87]:
c = np.arange(10, 50)
print(c[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [88]:
d = np.arange(0, 9).reshape([3, 3])
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [89]:
e = np.array([1, 2, 0, 0, 4, 0])
e = np.nonzero(e)[0]
print(e)

[0 1 4]


#### 11. Create a 3x3 identity matrix

In [90]:
f = np.identity(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [91]:
g = np.random.randint(0, 100, 100).reshape([10, 10])
print(g.min())
print(g.max())

0
99


#### 15. Create a 2d array with 1 on the border and 0 inside

In [92]:
h = np.zeros((5, 5))
h[0,:] = 1
h[-1,:] = 1
h[:,0] = 1
h[:,-1] = 1
print(h)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [93]:
i = np.zeros((8,8))
i[1::2, ::2] = 1
i[::2, 1::2] = 1
print(i)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [94]:
j = np.array([1, 4, 6, 8, 10, 3, 7, 2])
j[(j >= 3) & (j <= 8)] *= -1
print(j)

[ 1 -4 -6 -8 10 -3 -7  2]


#### 29. How to round away from zero a float array ?

In [95]:
k = None

#### 30. How to find common values between two arrays?

In [96]:
l = None

#### 36. Extract the integer part of a random array using 5 different methods

In [97]:
m = np.random.uniform(0,10,10)

In [98]:
print(np.floor(m))
print(np.ceil(m))
print(np.trunc(m))
print(m.astype(int))
print(np.vectorize())

[7. 0. 7. 7. 3. 3. 5. 0. 7. 4.]
[8. 1. 8. 8. 4. 4. 6. 1. 8. 5.]
[7. 0. 7. 7. 3. 3. 5. 0. 7. 4.]
[7 0 7 7 3 3 5 0 7 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [99]:
n = np.tile(np.arange(5), (5, 1))
print(n)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [100]:
o = np.linspace(0, 1, 12)[1:-1]
print(o)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [101]:
p = np.random.random(10)
p.sort()
print(p)

[0.09049769 0.15099455 0.3568897  0.4705566  0.58769727 0.801483
 0.83557312 0.95240405 0.96180303 0.96737861]


#### 42. Consider two random array A and B, check if they are equal

In [102]:
q = np.random.random(10)
r = np.random.random(10)
print(np.array_equal(q, r))

False


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [103]:
s = np.random.random(10)
s[s.argmax()] = 0
print(s)

[0.79154714 0.35559974 0.57175887 0.11389351 0.41106888 0.18031028
 0.76572529 0.21453571 0.         0.66920154]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [104]:
t = np.random.uniform(0,100,10)

In [105]:
scalar = 50
closest_value = t[np.abs(t - scalar).argmin()]
print(scalar, closest_value)

50 43.51242299385169


#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [106]:
u = np.random.random((10,2))


In [107]:
distances = np.sqrt(((u[:, np.newaxis, :] - u[np.newaxis, :, :]) ** 2).sum(axis=2))
print(u, distances)

[[0.02737611 0.98244754]
 [0.31783306 0.58960856]
 [0.49585328 0.69843606]
 [0.662314   0.41216844]
 [0.98470996 0.59528686]
 [0.0617719  0.20390926]
 [0.37168358 0.24315827]
 [0.67377249 0.72576122]
 [0.73386783 0.53915181]
 [0.82949966 0.90879016]] [[0.         0.48855676 0.54784431 0.85344266 1.0326575  0.77929772
  0.81553434 0.69549706 0.83405136 0.80549836]
 [0.48855676 0.         0.20864952 0.38749466 0.66690107 0.46295925
  0.35061044 0.38109109 0.4190833  0.60305853]
 [0.54784431 0.20864952 0.         0.33114698 0.49962047 0.65801474
  0.47190675 0.1800053  0.28639553 0.39442205]
 [0.85344266 0.38749466 0.33114698 0.         0.37077151 0.6356278
  0.33620006 0.31380205 0.14575571 0.5240078 ]
 [1.0326575  0.66690107 0.49962047 0.37077151 0.         1.00249243
  0.70696244 0.33720271 0.25704653 0.34982075]
 [0.77929772 0.46295925 0.65801474 0.6356278  1.00249243 0.
  0.31238715 0.80428489 0.75106624 1.04223941]
 [0.81553434 0.35061044 0.47190675 0.33620006 0.70696244 0.31238715


#### 57. How to randomly place p elements in a 2D array?

In [108]:
v = np.zeros((5, 5), dtype=int)
positions = np.random.choice(5 * 5, 5, replace=False)
np.put(v, positions, 1)
print(v)

[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [1 0 1 1 0]]


#### 58. Subtract the mean of each row of a matrix

In [109]:
w = np.random.random((5, 5))

row_means = w.mean(axis=1, keepdims=True)
result = w - row_means
print(w, result)

[[0.84295363 0.47521552 0.37114081 0.74729138 0.16723156]
 [0.90017106 0.0224779  0.38999481 0.10531432 0.02204958]
 [0.17207853 0.91034755 0.47059361 0.32948084 0.71287322]
 [0.90024896 0.61634968 0.9922393  0.98971509 0.51768907]
 [0.84457662 0.4197709  0.19453039 0.78965267 0.79402306]] [[ 0.32218705 -0.04555106 -0.14962577  0.2265248  -0.35353502]
 [ 0.61216952 -0.26552363  0.10199328 -0.18268721 -0.26595195]
 [-0.34699622  0.3912728  -0.04848114 -0.18959391  0.19379847]
 [ 0.09700054 -0.18689874  0.18899088  0.18646667 -0.28555935]
 [ 0.23606589 -0.18873982 -0.41398034  0.18114194  0.18551233]]


#### 59. How to sort an array by the nth column?

In [110]:
x = np.random.randint(0, 100, (5, 5))
n = 2
sorted_indices = np.argsort(x[:, n])
sorted_array = x[sorted_indices]
print(n, sorted_array)

2 [[40 22 16 87 64]
 [69 31 45 54 81]
 [54 66 52 35 94]
 [81 37 79 12 91]
 [49  3 89 82  0]]


#### 60. How to tell if a given 2D array has null columns?

In [111]:
y = np.array([
    [1, 0, 3],
    [4, 0, 6],
    [7, 0, 9]
])

# Check for null columns
null_columns = np.all(y == 0, axis=0)

print(y, null_columns)

[[1 0 3]
 [4 0 6]
 [7 0 9]] [False  True False]


#### 61. Find the nearest value from a given value in an array

In [112]:
z = np.random.uniform(0,1,10)
value = 0.5

In [113]:
nearest_value = z[np.abs(z - value).argmin()]
print(z, value, nearest_value)

[0.6797468  0.30926392 0.81744493 0.13225571 0.86453354 0.27053069
 0.90574314 0.97381738 0.80469346 0.5761265 ] 0.5 0.5761265003927198


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [114]:
A = np.array([1, 2, 3, 4, 5])
B = np.zeros(len(A) * 4 - 3, dtype=int)
B[::4] = A
print(B)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 72. How to swap two rows of an array?

In [115]:
import numpy as np

C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row1, row2 = 0, 2
C[[row1, row2]] = C[[row2, row1]]
print(C)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [116]:
D = np.array([True, False, True, False])
np.logical_not(D, out=D)
print("Negated boolean array:", D)

float_array = np.array([1.0, -2.0, 3.0, -4.0])
float_array *= -1
print("Sign-changed float array:", float_array)

Negated boolean array: [False  True False  True]
Sign-changed float array: [-1.  2. -3.  4.]


#### 83. How to find the most frequent value in an array?

In [117]:
E = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
most_frequent_value = np.bincount(E).argmax()
print("Most frequent value:", most_frequent_value)

Most frequent value: 4


#### 89. How to get the n largest values of an array

In [118]:
F = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
n = 3

n_largest_values = np.partition(F, -n)[-n:]
n_largest_values = np.sort(n_largest_values)[::-1]

print("The", n, "largest values are:", n_largest_values)

The 3 largest values are: [9 8 7]
